# Generated by Django 5.0.6 on 2024-05-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='authors',
            new_name='author',
        ),
    ]
